clinicjs/node-clinic-bubbleprof

test/visualizer-layout-node-allocation.test.js
test/visualizer-layout-positioning.test.js
test/visualizer-layout-scale.test.js
test/visualizer-layout.test.js
visualizer/draw/bubbleprof-ui.js
visualizer/layout/index.js
visualizer/layout/layout.js
visualizer/layout/positioning.js

We have a `debugMode` setting which is applied in many tests and can be turned on during dev work by modifying `visualizer/main.js`, which keeps and exposes some data which would otherwise be discarded. Currently it's applied as a setting to instances of DataSet.
This PR, spun out of some work on collapsedLayoutNode ids, shares this setting with instances of Layout (including sublayouts) created from the same dataSet, so that Layout code can be debugMode-only. 
It also updates some tests which create Layout instances in an artificial way calling `new Layout()` directly, which could cause the settings to become out of sync.
It doesn't change anything in outputs or tests, but allows us to store Layout data in debug mode only and write tests that access data which would otherwise be …

Share DataSet's debugMode setting with Layout

---

test/visualizer-layout-node-allocation.test.js
test/visualizer-layout-positioning.test.js
test/visualizer-layout-scale.test.js
test/visualizer-layout.test.js
test/visualizer-validation.test.js
visualizer/draw/bubbleprof-ui.js
visualizer/layout/collapsed-layout.js
visualizer/layout/index.js
visualizer/layout/layout-node.js
visualizer/layout/layout.js
visualizer/layout/positioning.js
visualizer/validation.js

Previously, collapsedLayoutNode ids were based on concatenations of the IDs of the nodes they contain, and look like this:
```
clump:C19,C20,C21,C22,C23,C24
clump:A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21
clump:A16,A19
```
The hashes used to expose the currently selected node, if a collapsed node is selected, are based on chains telling Bubbleprof what jumps to make to find a particular node (because collapsedLayoutNodes are only created during the sublayout creation process). Previously, they looked like this:
```
15896.clinic-bubbleprof.html#lclump:C19,C20,C21,C22,C23,C24|m
15896.clinic-bubbleprof.html#lclump:A16,A19|lclump:A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21|c3
```
Or to give an extreme example:
```
7078.clinic-bubbleprof.html#lclump:A71,A79,A80,A85,A92,A93,A98,A103,A1 …
```

 Simpler collapsed node ids, allowing url-encoding-safe hashes

---

test/visualizer-layout-layer.test.js
test/visualizer-layout-scale.test.js
visualizer/layout/collapsed-layout.js
visualizer/layout/layout.js
visualizer/layout/scale.js
visualizer/layout/stems.js

Fixes a rare but serious bug creating broken layouts on clicking into clusterNodes with very many aggregateNodes.
On digging into this I found it seems to happen when the total of the (unscalable) gaps between nodes exceeds the space available.
Here are a couple of 'before' examples:
https://upload.clinicjs.org/public/1e48153768a19dcf5bac7c225571945beb1fa282f022a767e135386ba14eb96c/1005.clinic-bubbleprof.html#c3 - 5,068 aggregate nodes in one cluster node
https://upload.clinicjs.org/public/39a458eeb928801e0cb2ad69cfb2108358fa3c72be6ac44a4e9b6ff9d413827d/21608.clinic-bubbleprof.html#c14 - 1,115 aggregate nodes in one cluster node
This PR fixes this by taking the total length of these unscalable gaps in the longest chain in the layout and adding it to the height of the space which is used …

Fix extremely large sublayouts (1,000+ nodes, chains 100+ long)

---

appveyor.yml
test/integration-servers.test.js

Reason for `Windows fix`:
Unix
Windows

Upgrade appveyor to use Node 10 

---

test/visualizer-layout.test.js
visualizer/data/data-node.js
visualizer/layout/layout-node.js

Not ready to merge yet, needs some tests - but first it needs some human testing to make sure it is actually giving names which reflect what is interesting inside a collapsed node.
So please try this out and dig around looking for cases where what you get when you click into a collapsed node is not what you might have expected from its name.
(tip: it's now possible to tell by looking if something is a collapsed node or not, they use `&` as a seperator while clusterNodes use `+`. This isn't something we'd necessarily expect or want users to notice, but it can be useful for debugging or advanced users maybe)

Give collapsedNodes names by interestingness

---

visualizer/layout/collapsed-layout.js

A very rare bug, but a serious one which causes an error and stops a layout from loading.
This happens if:
- a node is collapsed while collapseVertically is iterating through its children, 
- then, one of those children meets the criteria whereby the `combineLayoutNodes` method cancels itself, 
- then, another of its children attempts to collapse into the same group. 
When the method cancelled itself, it did so with `return`, removing the collapsed node from the loop. It then tries to collapse the next collapsible child into a node that was already ejected, hitting an error like:
```
Cannot combine nodes - clump/stem mismatch
```
This PR keeps the previous value of `combine` if `combineLayoutNodes` returns a falsey value (if it doesn't cancel, it returns a collapsedLayoutNode object). …

Keep previous value of combined layoutNode if combineLayoutNodes cancels

---

visualizer/layout/collapsed-layout.js

A basic fix for an issue mentioned in https://github.com/nearform/node-clinic-bubbleprof/pull/237
We have limit on node collapsing of 3 intended to stop views where everything is collapsed, where you click into the one big node and get the same identical view where everything is collapsed. However, it counts uncollapsible shortcutNodes (arrows), which means you can get the endless collapse everything problem if the view contains two or more shortcuts
https://upload.clinicjs.org/public/0db071669f1c0f7256fde9fd42571ab57bd684444de295415c90d254f6425bb1/1005.clinic-bubbleprof.html#x2385-x4992-c3
This PR only counts non-shortcuts when checking if the minimumNodes limit has been reached. We could still do with a smarter collapse limit, but this prevents impossible-to-enter views and infinite …

Don't count shortcutNodes when checking minimumNodes

---

test/visualizer-layout-scale.test.js
test/visualizer-layout.test.js
visualizer/layout/collapsed-layout.js
visualizer/layout/layout.js
visualizer/layout/scale.js
visualizer/layout/stems.js

Fixes the leftover issue described here where sometimes, a view can contain a chain of nodes just over the collapse threshold that contains too many nodes to fit into the space assigned for collapsing or a reasonable screen.
[note: these are still affected by the performance problem for super-large cluster nodes mentioned previously, so links to samples will be slow to load)
Before:
https://upload.clinicjs.org/public/cabda786c514e49ad25ad137dae1d14730c3146a95777a111b407a4e4abd5642/1005.clinic-bubbleprof.html#x4-c3
This PR does a pre-calculation before collapsing nodes to check that there won't be any stems too long (too many unscalable gaps between nodes) to be scaled to fit into a reasonable view. If so, it increases the collapse threshold, collapsing more nodes, and repeats until it has …

Adjust collapse threshold to ensure that the layout can fit in a reasonable window

---

analysis/index.js
analysis/raw-event/join-as-raw-event.js
index.js
test/analysis-raw-event-join.test.js

Did a lot of back and forth with this, but this seems to work quite nicely to solve #198
Basically ends the raw input data streams if more than 50% of the available heap has been used, and then only use that amount of data to do the analysis. When investigating this, it seems to produce the same amount of results as adding more memory.
For performance reasons it only checks the available heap every 4096 ticks.

cut data streams when running low on memory

---

format/trace-event-decoder.js
package.json

Used `clinic flame` to profile latest bubbleprof a bunch and the flamegraph kept showing JSONStream being on the top of the stack *a lot*. This makes sense as we use a ton of time parsing the trace events data.
To try and speed it up I wrote a specialised parser for the trace events format. This resulted in a 2x speed boost on my machine. It's still on top of the stack a ton (@davidmarkclements would love to try using your optimised schema based JSON parse here to see if it has any effect).
```
time node $(which clinic) bubbleprof --visualize-only 25547.clinic-bubbleprof
Generated HTML file is 25547.clinic-bubbleprof.html
You can use this command to upload it:
clinic upload 25547.clinic-bubbleprof
real	0m10.103s
user	0m14.143s
sys	0m0.654s
```
Resulting flamegraph: …

Use specialised parser for speed boost

---

analysis/cluster/cluster-node.js
analysis/cluster/combine-as-cluster-nodes.js
test/analysis-cluster.test.js

Makes the analysis ~20% faster on my machine on profiles that have a ton of clusters.
Works by only sorting the `clusterNode.nodes` array *just* before they are pushed to the pipeline (they aren't used before).
Might experiment with using [mafintosh/value-sort](https://github.com/mafintosh/value-sort) to speed it up even more, but this removes it as a hot method so good enough.
https://upload.clinicjs.org/public/3ab41478efac738d86e1536b98dcdd460fa3f29983f11473a6dc8a4e61a9077f/10715.clinic-flame.html
https://upload.clinicjs.org/public/c44fe8e71aa9a217b74efe40d2609fe1564df7d82ad57add5426ade72465c30c/10928.clinic-flame.html

Only sort clusterNode.nodes just before they are pushed. Fixes #242

---

format/trace-event-decoder.js

This makes sure both formats are accepted.

The format for the trace events changed partially

---

index.js
injects/no-cluster.js
test/cmd-no-cluster.script.js
test/cmd-no-cluster.test.js

See https://github.com/davidmarkclements/0x/pull/155
The test that does `cluster.fork()` generates output so I moved that into a subprocess. The test that just does `require('cluster')` doesn't generate any output so I left it inline.

Throw error if a cluster subprocess is forked

---

visualizer/draw/area-chart.js

As mentioned in this review comment - https://github.com/nearform/node-clinic-bubbleprof/pull/264#issuecomment-419414256
We can improve the performance of AreaChart.draw() enough to call it without debouncing on resizing the containing window, if we stop calling AreaChart.createPathsForLayout() on every draw event and instead call it only when needed: 
- on first initialisation of the chart
- on a change to the main layout or sublayout being viewed
- for the chart within the hover box, on hovering a new node
Should be no appearance or functionality changes, just improved efficiency on draw() events that include the area chart.

Only redraw area chart paths when necessary

---

visualizer/draw/area-chart.js
visualizer/draw/breadcrumb-panel.js
visualizer/draw/bubbleprof-ui.js
visualizer/draw/frames.js
visualizer/draw/hover-box.js
visualizer/draw/lookup.js
visualizer/draw/svg-node-diagram.js

This patch replaces the `history` array and hash URLs with a `pushState` based solution. For clarity I'll refer to the `history` array that stored UI instances as `customHistory`.
Demo: https://upload.clinicjs.org/public/02047f8379fae585fcdc17a644648fcd765fa46aa20ddf355761dafaae8698ae/2575.clinic-bubbleprof.html
TODO:
Details:
- On load, we set the current history state to `{ initial: true }` using `replaceState`. We can then do `!window.history.state.initial` to check if we have any entries in the history, instead of checking `customHistory.length`, to decide if the back button should be shown.
- BubbleprofUI instances now have a `getHash()` method that returns a URL-compatible ID, just like the `location.hash` assignments before
- On Bubbleprof 'navigation' events, we call `getHash()` …

Browser history support

---

analysis/stack-trace/frames.js
analysis/system-info.js
collect/system-info.js
test/analysis-util/system-info.js
test/analysis.test.js
visualizer/draw/svg-node-section.js

Spelling "separate" and its variants as "seperate" like this is apparently one of the most common spelling mistakes in English. We had some issues in Flame caused by using similar system info logic to this (containing the typo) then other code using the correct spelling. So, best to have correct spelling everywhere.
Since data collected before this PR will have written `pathSeperator` into the system-info files, this checks for either `pathSeperator` or `pathSeparator` when reading system info, so that `visualize-only` and `visualize-all` still work on old samples.

Correct typo, "Seperator" -> "Separator", with backwards compatibility for old data

---

README.md
index.js
injects/logger.js
package.json
test/cmd-dest.test.js

Passes the value of `options.dest` to `getLoggingPaths()` calls, basically in an identical way as Doctor.
mkdirp is now needed in injects/logger.js because the output path isn't always just a single directory inside the working directory anymore.

Add --dest flag.

---

index.js
test/cmd-collect-exit.test.js

Related to issue #277  and nearform/node-clinic#73
Do not throw on client application termination.
Only report error and continue processing the traces.
Adjusted handler and updated test that check on error throwing.

do not abort on process exit code

---

package.json

Should fix https://github.com/nearform/node-clinic-bubbleprof/issues/279 - basically the same as https://github.com/nearform/node-clinic-doctor/pull/197 for Doctor.
- Raise timeout limits by quite a lot because we have confirmed timeouts on CITGM
- Bigger raise for coverage tests

Raise tap timeout limit

---

test/cmd-collect.test.js
test/collect-stack-trace.test.js

In v8 7.0, Array.sort() was moved from a JS-based implementation to
Torque:
https://github.com/v8/v8/commit/fa11e2ac0380948a2f57963e6651402c3ca07d04
This means Array.sort() isn't in v8's `array.js` file anymore.
Apparently the goal is to eventually move all or most JS implementations
of builtins like Array to to Torque, so 'native' is a shrinking
category. We may need to do something to detect those Torque things?

Fix native stack trace test and remove TIMERWRAP assertion in Node 11

---

index.js
test/cmd-collect-analysing.test.js

for consistency among tools, emit an 'analysing' event when starting the analysis that's done during the collect phase. for doctor and bubbleprof, that's not much (just moving a file).

Emit "analysing" event as soon as process exits.

---

test/integration-servers.test.js
test/servers/basic.js
test/servers/express.js
test/servers/external.js
test/servers/latency.js
test/servers/quine.js

this may :pray: address the citgm failure. I still can't reproduce it locally, this is somewhat of a brute force approach.
@mcollina i think you mentioned you could run things in citgm environment? it would be interesting to see if this works there before we fully re enable it if possible…this error happened in at least Ubuntu 14.04 and 18.04

unlink socket before listen() if it exists.

---

format/abstract-decoder.js
package.json

I've stumbled on a couple of these with Node 10. I think it's better print them out, so that we can add unit tests for those.

Print useful info for decoding errors

---

test/visualizer-validation.test.js
visualizer/layout/collapsed-layout.js
visualizer/validation.js

This extracts a couple of fixes from some older performance work that became unweildy. It doesn't fix all the performance issues, but it does isolate and fix two important ones while some bugs in the other perf work are being fixed:
- Some excessive iteration when generating unique key IDs
- Some repeated logic when checking if the amount of layoutnode collapsing has dropped below threshold
Both of these become problems when there are more than around a thousand nodes in a layout.
Example before (for me, it takes around 27 seconds to open the big 5068-node node):
https://upload.clinicjs.org/public/78eb0733e85ee8e1eec54e3c81bc13aa6ed801ca4b612cb954837e47cd1b4cac/1005.clinic-bubbleprof.html
Example after (for me, it now takes around 4 seconds): …

Remove some performance bottlenecks from very large layouts

---

visualizer/draw/area-chart.js
visualizer/draw/hover-box.js
visualizer/draw/side-bar-drag.js

This mostly improves the performance of updates and redraws of the area charts, which in turn greatly improves the performance of the hover boxes on large profiles. It also includes a fix for a small bug where hovering over an area chart can result in a colour getting stuck highlighted.
For example, **before**, here after opening the big circle (happens automatically on load from hash), on my machine hovering over any node has a very noticeable delay of around four seconds:
https://upload.clinicjs.org/public/3ffbe38013d868abce48123908c28ef10bc4cedb078d09848f51706f47b47dd3/1005.clinic-bubbleprof.html#c3
**After**, it's greatly reduced (maybe up to half a second on my machine):
https://upload.clinicjs.org/public/f447aca7199bb0661f81fbd6d954b58398b70195b7aacb8cd9b2a8b9924300cc/1005.clinic-bub …

Improve performance and tidy up area chart / hover code

---

index.js
package.json
visualizer/main.js
visualizer/style.css

This strips out duplicated build scripts for JS and CSS compilation and uses a template function to import a consistent UI chrome along with necessary styles and behaviours showing a tray with a command to copy when you click the 'Ask an expert' button.
**[Example output](https://upload.clinicjs.org/public/76e375b8e9ade6560a00e012a2815459a7e67b3bbb074d50f4ed3ee7bb338efe/45498.clinic-bubbleprof.html)**

Use JS/CSS build scripts and main template from Clinic Common

---

visualizer/draw/area-chart.js

Fixes https://github.com/nearform/node-clinic-bubbleprof/issues/306
Before, the area chart used `parentContent.constructor.name` to identify if it was in the hover box or the sidebar. This seems to have recently become unreliable in a strange way - using the latest Master, profiles generated through `npm run visualize-all` show the hover box `constructor.name` as HoverBox, as expected, but the exact same local code linked through `clinic bubbleprof` generates profiles where the contructor name is that of the _parent_ class, `HtmlContent`.
I've written up a separate issue to find out why the two give outputs that behave differently - https://github.com/nearform/node-clinic-bubbleprof/issues/307 - this PR is to ensure that this inconsistency doesn't cause bugs.
This was generated using …

Don't identify hoverbox by content constructor name

---

debug/visualize-watch.js
visualizer/draw/area-chart.js
visualizer/draw/d3-subset.js
visualizer/style.css

Canvas should be a better performer than SVG when there are more than 1000 node points to render. 
This PR migrates rendering to  canvas of the Area Chart that appears on the right hand column, and the hover-panel in the main layout.
The approach taken was to
- maintain SVG for the supporting chart data - axes, and the slice indicator
- create a custom D3 element to offer some separation between generic data manipulation and the draw to canvas
- introduce a the canvas element and position it in the chart area
- add a hidden colour mapping canvas element for tracking mouse activity (as rendered elements are not available to event handlers the way they are available to SVG nodes)
For comparison: 
before:
after:

Render area chart as canvas instead of SVG

---

analysis/aggregate/name-aggregate-nodes.js
analysis/barrier/name-barrier-nodes.js
package.json

[Trello: Update clusterNode names to better indicate contents](https://trello.com/c/YXWvSKCE/733-3-update-clusternode-names-to-better-indicate-contents)
This looks to improve the labelling  for userland information in clusterNodes - we can extract better information from the AggregateNode Frames when the initial label is too generic - and pass that up to the ClusterNode. 
From the example in the above Trello Issue: 
Before: 
After: 
Some other generic labelling _may_ be more valuable in places where the `type` is displayed (e.g. `nextTick` - here is an example where the more specific information may or may not be of value. Should we refine these rules?

More specific userland names for node clusters

---

analysis/stack-trace/frames.js
test/analysis-aggregate-mark-module.test.js

Fixes #303, where the topmost frame in a stack for an external module was part of an eval() call. When marking aggregate nodes it tried to get the module name of the topmost frame in the module, which would be `null` for eval frames.
eval frames contain a file path in brackets `eval at parentFn (/path.js:X:Y)` inside the `evalOrigin` property, so we can fall back to that.

Detect module name for eval frames

---

index.js

Seems this doesn't matter anymore
https://github.com/nearform/node-clinic-doctor/pull/132
But ths still relates to current state
https://github.com/nearform/node-clinic/issues/148
So there might be changes done to fix NODE_PATH back, for legacy projects.

Fix NODE_PATH for legacy projects

---

test/cmd-no-cluster.cluster.js
test/cmd-no-cluster.script.js

same as https://github.com/nearform/node-clinic-doctor/pull/242
cluster.fork doesn't work if you use it from `node -e`, this test should never have worked but it passed silently for a long time!

fix cluster test

---

test/cmd-collect.test.js
test/integration-timeout.test.js

https://github.com/nodejs/node/pull/30624 means the `-e` flag now uses the esm module initialization code which includes a Promise.resolve() call which generates a trace event in Node.js 12.16.
Closes https://github.com/nearform/node-clinic-bubbleprof/issues/352

Fix tests on Node 12.16

---

index.js
injects/logger.js
package.json

Detect transpiled code by using a median of function name length and provide warning to the user. Also checks file for a source map comment.

Transpiled code warning

---

index.js

Pass the tool version to the html template.
[Issue FK02](https://trello.com/c/vgIgBXME/843-fk02-visibility-of-system-status)

Display bubbleprof version beneath logo

---

test/cmd-collect.test.js
test/integration-timeout.test.js
visualizer/data/callback-event.js

Fixes a reported bug where the incorrect segments start time was being set to after end time
before: 
after: 
note: the provided data _does_ contain a separate instance of inverted before/after values - which is handled  with a warning
Fixes #363

fix: visualizer source delayStart must precede source before

---

.taprc
index.js
injects/logger.js
test/format-stack-trace.test.js

It aims to solve: https://github.com/clinicjs/node-clinic/issues/293#issuecomment-954354390.
However, I'm not entirely sure if it's the best approach, It was not documented anywhere in nodejs streams documentation but it aims to solve the behavior added in `v15.9.0`
I'm doing some tests to see if it affects the result data.
**Important:** see https://github.com/clinicjs/node-clinic-bubbleprof/pull/389#issuecomment-1001210698

fix: increase highWaterMark value to fix file descriptor issue on v16+

---

collect/system-info.js

Address: #383 
The `asyncWrapProviders` wasn't backported to v16 yet, once it's done a new PR will be created.

update: remove deprecation warning on v17.2+
